apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Repo-2
  annotations:
    github.com/project-slug: sampgreenwell-cyber/Repo-2
spec:
  type: other
  lifecycle: unknown
  owner: guests
