name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sampgreenwell-cyber/todo-app

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: Test Docker container
      run: |
        docker run -d -p 3000:3000 --name test-app ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        sleep 10
        curl -f http://localhost:3000 || exit 1
        docker stop test-app
        docker rm test-app

    - name: Push Docker image
      if: github.event_name == 'push'
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Configure AWS credentials
      if: github.event_name == 'push'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Update kubeconfig for EKS
      if: github.event_name == 'push'
      run: |
        aws eks update-kubeconfig --region us-east-2 --name adorable-jazz-gopher

    - name: Deploy to EKS
      if: github.event_name == 'push'
      run: |
        kubectl apply -f k8s/deployment.yaml --validate=false
        kubectl apply -f k8s/service-eks.yaml --validate=false
        kubectl set image deployment/todo-app todo-app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} --validate=false

    - name: Get service URL
      if: github.event_name == 'push'
      run: |
        kubectl get service todo-app-service